server:
  port: 8086
spring:
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/email-db
    username: postgres
    password: 1234
  cloud:
    function:
      definition: notificationBinding;
    stream:
      default-binder: kafka_default
      bindings:
        notificationBinding-in-0:
          destination: new-notification-event
          binder: kafka_default
          useNativeDecoding: true
        notificationBinding-out-0:
          destination: notification-processed
          binder: kafka_default
          useNativeDecoding: true
      binders:
        kafka_default:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    default:
                      consumer:
                        configuration:
                          session.timeout.ms: 10000
                          max.poll.records: 10
                      producer:
                        compressionType: gzip
                        configuration:
                          max.request.size: 100000
                    binder:
                      autoAddPartitions: true
                      autoCreateTopics: true
                      requiredAcks: -1
                      minPartitionCount: 3
                      replicationFactor: 1
                      serdeError: logAndContinue
                      brokers: localhost:9092
mailgun:
  apikey: 2dec05a0664f61703e6d6edb736ccbf5-911539ec-1f811008
  url: frantrainer.es
s3:
  bucket: bucket-prueba
  endpoint: http://localhost:4566
  accessKey: test
  secretKey: test
